"""Dependency graph of the simulation model: nodes (components) and directed
edges ("reads from" relations), extracted from the paper's Section 3 tick
order, entity definitions, policy parameters, and outcome measures.

Single source of truth for the static appendix figure
(make_figures.fig_dependencies) — keep docs/dependency-graph.html in sync
when editing.
"""

GROUPS = {
    "tech": {"color": "#7F77DD", "name": "Technology and data"},
    "firm": {"color": "#D85A30", "name": "Firms"},
    "lab": {"color": "#1D9E75", "name": "Workers and matching"},
    "pol": {"color": "#D4537E", "name": "Policy levers"},
    "out": {"color": "#888780", "name": "Emergent outcomes"},
}

# (id, group, label)
NODES = [
    ("taskdata", "tech", "Task data"),
    ("capability", "tech", "Capability"),
    ("aiprice", "tech", "AI price"),
    ("quality", "tech", "Task quality"),
    ("augment", "tech", "Augmentation"),
    ("roi", "firm", "Adoption ROI"),
    ("peer", "firm", "Peer imitation"),
    ("hurdle", "firm", "Adoption hurdle"),
    ("adoption", "firm", "Task adoption"),
    ("price", "firm", "Firm price"),
    ("demand", "firm", "Demand factor"),
    ("targets", "firm", "Headcount targets"),
    ("layoffs", "firm", "Layoffs"),
    ("vacancies", "firm", "Vacancies"),
    ("exit", "firm", "Firm exit"),
    ("entry", "firm", "AI-native entry"),
    ("separations", "lab", "Separations"),
    ("searchers", "lab", "Job searchers"),
    ("distance", "lab", "Occupation distance"),
    ("matching", "lab", "Matching"),
    ("mp", "lab", "Marginal product"),
    ("wages", "lab", "Wages"),
    ("reservation", "lab", "Reservation wage"),
    ("discourage", "lab", "Discouragement"),
    ("benefit", "pol", "Benefit level"),
    ("subsidy", "pol", "Retraining subsidy"),
    ("firingcost", "pol", "Firing cost"),
    ("mefficiency", "pol", "Matching efficiency"),
    ("unemployment", "out", "Unemployment"),
    ("output", "out", "Output"),
    ("gini", "out", "Wage distribution"),
    ("beveridge", "out", "Beveridge curve"),
    ("pyramid", "out", "Pyramid inversion"),
]

EDGES = [
    ("taskdata", "quality"),
    ("capability", "quality"),
    ("capability", "augment"),
    ("taskdata", "augment"),
    ("taskdata", "distance"),
    ("quality", "roi"),
    ("aiprice", "roi"),
    ("wages", "roi"),
    ("roi", "adoption"),
    ("peer", "adoption"),
    ("hurdle", "adoption"),
    ("adoption", "peer"),
    ("entry", "adoption"),
    ("adoption", "price"),
    ("augment", "price"),
    ("price", "demand"),
    ("demand", "targets"),
    ("adoption", "targets"),
    ("augment", "targets"),
    ("targets", "layoffs"),
    ("firingcost", "layoffs"),
    ("targets", "vacancies"),
    ("demand", "exit"),
    ("exit", "searchers"),
    ("exit", "entry"),
    ("layoffs", "searchers"),
    ("separations", "searchers"),
    ("searchers", "matching"),
    ("vacancies", "matching"),
    ("distance", "matching"),
    ("mefficiency", "matching"),
    ("reservation", "matching"),
    ("matching", "wages"),
    ("mp", "wages"),
    ("reservation", "wages"),
    ("adoption", "mp"),
    ("augment", "mp"),
    ("subsidy", "mp"),
    ("benefit", "reservation"),
    ("searchers", "reservation"),
    ("searchers", "discourage"),
    ("discourage", "searchers"),
    ("searchers", "unemployment"),
    ("discourage", "unemployment"),
    ("demand", "output"),
    ("wages", "gini"),
    ("vacancies", "beveridge"),
    ("unemployment", "beveridge"),
    ("targets", "pyramid"),
]

# Hand-tuned positions for the static figure (x in [0, 10], y in [0, 8]),
# arranged as a left-to-right causal flow: technology/policy -> firm and
# labour blocks -> outcomes. The interactive HTML uses a live force layout
# seeded by the same cluster structure.
POSITIONS = {
    "taskdata": (0.6, 3.6),
    "capability": (0.6, 4.8),
    "aiprice": (0.6, 6.0),
    "quality": (2.1, 5.2),
    "augment": (2.3, 3.9),
    "hurdle": (3.2, 7.4),
    "peer": (5.6, 7.4),
    "roi": (3.4, 5.9),
    "adoption": (4.4, 6.4),
    "entry": (6.9, 6.8),
    "exit": (7.4, 5.6),
    "price": (5.5, 5.4),
    "demand": (6.5, 4.6),
    "targets": (5.1, 4.2),
    "layoffs": (4.3, 3.2),
    "vacancies": (6.0, 3.2),
    "separations": (2.4, 2.7),
    "searchers": (3.7, 2.3),
    "discourage": (2.7, 1.3),
    "distance": (1.1, 2.2),
    "matching": (5.2, 2.1),
    "mp": (2.9, 0.5),
    "reservation": (3.9, 1.2),
    "wages": (5.7, 1.1),
    "benefit": (0.8, 1.2),
    "subsidy": (0.8, 0.4),
    "firingcost": (2.4, 4.7),
    "mefficiency": (6.6, 1.4),
    "unemployment": (9.3, 2.4),
    "output": (9.3, 4.8),
    "gini": (9.3, 1.2),
    "beveridge": (9.3, 3.5),
    "pyramid": (9.3, 5.8),
}
